(defpackage #:demiurge/tests
  (:use #:cl #:rove #:demiurge #:demiurge/improve #:demiurge/observe
        #:demiurge/serve #:demiurge/ingest #:demiurge/workflows
        #:demiurge/bundle)
  (:shadowing-import-from #:demiurge #:run-tests)
  (:local-nicknames (#:bb #:blackboard-protocol)
                    (#:cap #:capability-protocol)
                    (#:agent #:ai-agent-protocol)
                    (#:llm #:llm-protocol)
                    (#:conv #:conversation-protocol)
                    (#:steer #:steer-protocol)
                    (#:eval #:eval-protocol)
                    (#:task #:task-protocol)
                    (#:tel #:telemetry-protocol)
                    (#:log #:log-protocol)
                    (#:rag #:rag-protocol)
                    (#:obs #:demiurge/observe)
                    (#:mcp #:mcp-protocol)
                    (#:a2a #:a2a-protocol)
                    (#:ag-ui #:ag-ui-protocol)
                    (#:mail #:mail-protocol)
                    (#:obj #:object-store-protocol)
                    (#:web #:websearch-protocol)
                    (#:doc #:doc-extract-protocol)
                    (#:wf #:demiurge/workflows)))

(in-package #:demiurge/tests)
