(defpackage #:demiurge/tests
  (:use #:cl #:rove #:demiurge #:demiurge/improve #:demiurge/observe)
  (:shadowing-import-from #:demiurge #:run-tests)
  (:local-nicknames (#:bb #:blackboard-protocol)
                    (#:cap #:capability-protocol)
                    (#:agent #:ai-agent-protocol)
                    (#:llm #:llm-protocol)
                    (#:conv #:conversation-protocol)
                    (#:steer #:steer-protocol)
                    (#:eval #:eval-protocol)
                    (#:task #:task-protocol)
                    (#:tel #:telemetry-protocol)
                    (#:log #:log-protocol)
                    (#:rag #:rag-protocol)
                    (#:obs #:demiurge/observe)))

(in-package #:demiurge/tests)
